### ISSUE TITLE
maven project에서 Repository를 설정하였지만 의존성을 찾지 못함.

### ISSUE THREAD

**Issue by urstory** [benelog/multiline#2]
![2015-04-08 11-22-58](https://cloud.githubusercontent.com/assets/8074890/7047305/9910d7fa-de46-11e4-832d-2d6293681ab0.png)

https://github.com/benelog/multiline/wiki/Maven-project-with-Eclipse 문서에서
Add the dependency in Maven 챕터에서 설정하라는 대로 하였지만 인식이 안됨.

무엇이 문제일까요?

**Comment by benelog** [comment]
혹시 command line에서 mvn compile을 해도 마찬가지 인가요?

**Comment by benelog** [comment]
@urstory 
jcenter에 배포했습니다.

<https://github.com/benelog/multiline/blob/master/multiline-string-usage/pom.xml> 과 같이 해도 에러가 나는지 한번 확인해주세요~

**Comment by benelog** [comment]
추가적인 피드백이 없으셔서 일단 이슈 종료하겠습니다.
