### ISSUE TITLE
maven repo link is not working

### ISSUE THREAD

**Issue by vladp** [benelog/multiline#4]
Hello, trying to use your Multiline annotations in my android project
However the maven link you provided in the instructions is not working 
https://raw.github.com/benelog/multiline/master/maven-repository

I am setting this up from my gradle.bulid
and tried both   raw.github and 
https://raw.githubusercontent.com/benelog/multiline/master/maven-repository

**Comment by benelog** [comment]
@vladp  I deployed the library to <http://jcenter.bintray.com> and changed pom.xml of a sample project. ( <https://github.com/benelog/multiline/blob/master/multiline-string-usage/pom.xml> )

With gradle, you can access it by following

```
repositories {
    jcenter()
}
```

or 

```
repositories { 
    maven { url "http://jcenter.bintray.com" } 
} 
```

**Comment by vladp** [comment]
Hello, thank you for the updates.
It works now.
  
I am getting some warnings as below (Android studio 1.4 on W10, 64bit, Java 1.7).
But the warning does not affect the function
-----
warning: No SupportedSourceVersion annotation found on org.adrianwalker.multilinestring.MultilineProcessor, returning RELEASE_6.
warning: Supported source version 'RELEASE_6' from annotation processor 'org.adrianwalker.multilinestring.MultilineProcessor' less than -source '1.7'
