### ISSUE TITLE
Support the annotation for local variable

### ISSUE THREAD

**Issue by codan84** [benelog/multiline#7]
Right now we have `@Target(ElementType.FIELD)` on the annotation, and so we can't use it for local variables. Could support for local variables be added?

**Comment by benelog** [comment]
It seems that annotation processing on local variables works in Java 8.
 
( http://stackoverflow.com/questions/3285652/how-can-i-create-an-annotation-processor-that-processes-a-local-variable )

I will consider it. To preserve backward compatibility,  It may introduce another annotation and processor for Java 8.

**Comment by benelog** [comment]
I realized that there's no way to get content of comments on local variables. `@Multiline` depends on Javadoc comments on field variables. 

I sorry that I  cannot resolve this issue.
